# Generated by Django 5.0.6 on 2024-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0002_administrador_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiaplicacionCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('is_especialista', models.IntegerField()),
                ('is_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'miaplicacion_customuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiaplicacionCustomuserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'miaplicacion_customuser_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiaplicacionCustomuserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'miaplicacion_customuser_user_permissions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
